# Generated by Django 4.1.2 on 2022-10-20 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_customer_options'),
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseSMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_send', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApplianceSMS',
            fields=[
                ('basesms_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sms.basesms')),
                ('appliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.appliance')),
            ],
            bases=('sms.basesms',),
        ),
        migrations.CreateModel(
            name='RegularSMS',
            fields=[
                ('basesms_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sms.basesms')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.customer')),
            ],
            bases=('sms.basesms',),
        ),
        migrations.DeleteModel(
            name='SMS',
        ),
    ]
