# Generated by Django 4.1.2 on 2022-10-21 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_basesms_appliancesms_regularsms_delete_sms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basesms',
            old_name='is_send',
            new_name='is_sent',
        ),
    ]
