# Generated by Django 4.1.2 on 2022-10-22 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0003_rename_is_send_basesms_is_sent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appliancesms',
            options={'verbose_name_plural': 'Appliance SMSes'},
        ),
        migrations.AlterModelOptions(
            name='basesms',
            options={'verbose_name_plural': 'Base SMSes'},
        ),
        migrations.AlterModelOptions(
            name='regularsms',
            options={'verbose_name_plural': 'Regular SMSes'},
        ),
        migrations.RemoveField(
            model_name='basesms',
            name='text',
        ),
        migrations.AddField(
            model_name='regularsms',
            name='text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
