# Generated by Django 4.1.2 on 2022-10-20 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ('name', 'phone')},
        ),
    ]
