# Generated by Django 4.1.2 on 2022-10-20 09:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('tx_hash', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('appliance', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='management.appliance')),
            ],
        ),
    ]
