# Generated by Django 4.1.2 on 2022-10-21 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_alter_transaction_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
